### ISSUE TITLE
version 1.19 

### ISSUE THREAD

**Issue by AnomalousDeity** [CleverNucleus/RelicEx#10]
Relicex version 3.2.2 for 1.19 says it requires cloth config v6 (i am using the most recent cloth config version for 1.19)

**Comment by CleverNucleus** [comment]
Hi there,
Would you be able to share an image/screenshot of the error message?
Thanks.

**Comment by AnomalousDeity** [comment]
I figured it out i had 3 versions of cloth config (old ones), for some reason it was only reading the lowest one before giving me the error, sorry for the trouble ^^'

**Comment by CleverNucleus** [comment]
No worries, I'm happy things worked out.
