### ISSUE TITLE
Game fails to render an armor drop

### ISSUE THREAD

**Issue by MemeLord32** [CleverNucleus/RelicEx#14]
Guess who's back with another crash? Me!

When I killed a zombie, it tried to drop an armor piece, and failed to do so.

https://pastebin.com/CCcn7xQF < - Crash Report

https://pastebin.com/XQBeeRaQ < - Modlist

Fabric Version: fabric-api-0.58.0+1.19
RelicEx Version: 3.2.3

**Comment by CleverNucleus** [comment]
Hi there,
This is a duplicate of #12; regardless, I appreciate the additional information.
Thanks.

**Comment by CleverNucleus** [comment]
Hi again,
I realise I closed this, but I am unable to replicate this crash. I am fairly certain about what is causing it - namely GeckoLib - and I have a solution, but since I cannot get it to crash in the first place I am unable to verify that my fix works. Any thoughts? @MemeLord32 
Thanks.
