### ISSUE TITLE
[Compatibility Request] Hide Armor Mod

### ISSUE THREAD

**Issue by cymophic** [CleverNucleus/RelicEx#15]
Link: https://www.curseforge.com/minecraft/mc-mods/hide-armor

Relic Ex Mod:
![image](https://user-images.githubusercontent.com/97153344/185851599-c393585e-8d66-4f68-9bbf-9682f67ceb1a.png)

Other Helmets:
![image](https://user-images.githubusercontent.com/97153344/185851690-3d129600-165a-4999-a37f-4424b83ba789.png)

**Comment by CleverNucleus** [comment]
Hi there,
Please see [here](https://github.com/Furgl/Hide-Armor/pull/12). In short, Hide-Armor does not currently support armor features added using the Fabric API, which is what RelicEx does.
Thanks.
