### ISSUE TITLE
Update for 1.19.2?

### ISSUE THREAD

**Issue by TripleDAK** [CleverNucleus/RelicEx#16]
No issue, love the mod and am incredibly grateful for you and the team's hard work on the other mods. Just curious if an update for 1.19.2 for fabric is possible?

**Comment by CleverNucleus** [comment]
Hi there,
Hopefully today (GMT).
Thanks.

**Comment by CleverNucleus** [comment]
Release for 1.19.2 has been made available on Modrinth and Github, pending approval on Curseforge.

**Comment by TripleDAK** [comment]
Thank you so much! Anyway to donate to the cause?

**Comment by CleverNucleus** [comment]
I appreciate it, but I am not accepting donations currently. 😃
