### ISSUE TITLE
Constitution does not go back down after unequipping amulet with constitution stat (1.16.5 forge)

### ISSUE THREAD

**Issue by Garwinium** [CleverNucleus/RelicEx#17]
as shown in this video you can repeatedly unequip and equip the constitution amulet and get seemingly infinite health
https://user-images.githubusercontent.com/92835818/189213731-4e7c6f11-e7d9-40cc-8ca3-788147e61271.mp4

**Comment by CleverNucleus** [comment]
Hi there,
This release is now deprecated and unsupported.
Thanks.

**Comment by Garwinium** [comment]
oh ok sorry I had this in a modpack so i didn't know the version it used was deprecated thanks
