### ISSUE TITLE
No Visual Changes

### ISSUE THREAD

**Issue by SdataG** [CleverNucleus/RelicEx#18]
I love your mods and would love to contact you about a custom variation (would pay for) 

But regarding my issue 

When equipping armor I see no stat changes in my stat window 

I would like to k ow what my armor doing (via end amount) in my stat window 

So far I can only see my own edit stats and nothing involving the equipment stat increase

**Comment by CleverNucleus** [comment]
Hi there,
Which version of RelicEx, PlayerEx and Data Attributes are you using? Are you playing with many other mods? Are there any you think could be conflicting or causing this behaviour?

Regarding a custom variation, I appreciate it, but I am not accepting commissions at this time.
Thanks.

**Comment by SdataG** [comment]
Then I guess I'll need to learn the api and how to code and build the mod
my self

Also no I have no external mods only your mod and supporting as my mod pack
is very early production

And all I did was kill a mob till it dropped an armor piece and put it on

Version is what ever the 1.18 version curseforge gives you

I could check later after work
