### ISSUE TITLE
Curseforge not hosting latest 1.16.5 version

### ISSUE THREAD

**Issue by darkshadow1809** [CleverNucleus/RelicEx#2]
Fixed this for you but wanted to report it just so you know it for the future :)

https://cdn.discordapp.com/attachments/231527759279685634/905121802324414514/unknown.png

https://cdn.discordapp.com/attachments/231527759279685634/905121944393875526/unknown.png

https://cdn.discordapp.com/attachments/231527759279685634/905122020000403506/unknown.png

As you can see when hosting a 1.16.5 pack with latest forge, the version of playerexrelics doesn't get updated to the latest version there is available, I have corrected this for you now by forwarding it to the correct people and it will be fixed within 24h.

I just wanted to let you know that this can happen and in the future if you would, be able to check if the latest version is actually available for download :-)! 

Thank you for your awesome work and happy modding!

PS: I forwarded this on the curseforge support discord Claycorp instantly forwarded it to the correct people.

**Comment by CleverNucleus** [comment]
Hi there,
I think there may be a misunderstanding here - there is and has only ever been one version of RelicEx released for Forge: 1.0.0 for 1.16.4/1.16.5. All other releases are for Fabric (I moved from Forge to Fabric early this year).

**Comment by darkshadow1809** [comment]
You're right, close this. I am a r*tard lol
