### ISSUE TITLE
Suggestion: Add a config file to modify the probabilty of the modifiers

### ISSUE THREAD

**Issue by ghost** [CleverNucleus/RelicEx#21]
I'm aware that you should be able to adjust these values with a datapack but I have had no end of difficulty trying to get that to work. So I was wondering if it be possible to have a config file in addition to the datapack functionality.

**Comment by CleverNucleus** [comment]
Hi there,
Using datapacks you have full configurability over nearly all aspects of the relic items and the attribute modifiers that are attached - I will not be providing a dedicated config for something that can already be done. I'm aware that the documentation on this specific facet of the mod is somewhat lacking, but I would still point you [here](https://github.com/CleverNucleus/RelicEx#configuring-relic-attributes-with-datapacks).
Thanks.

**Comment by ghost** [comment]
I actually feel like the datapack solution has a fairly large issue. That being that (and correct me if I'm mistaken) there is no way to have a datapack added into a newly created world by default. So modpack authors would either have to have the user add in a datapack every time they create a world or create a dummy mod with the datapack just to make sure it is always loaded.

**Comment by CleverNucleus** [comment]
You can add datapacks into newly created worlds. 

- For singleplayer, this is done through the world creation options GUI.
- For multiplayer, this can be done by:
  - Creating a singleplayer world and loading it up on your server.
  - Using mods like [Data Loader](https://www.curseforge.com/minecraft/mc-mods/data-loader) (although this specific one seems inactive) to load your datapack on initial world creation. The mod usually tells you how to do this and its a bit different for different mods.
  - Creating a dummy mod like you suggested ([Terralith](https://www.curseforge.com/minecraft/mc-mods/terralith), for example).
  - The standard method, simply running the server and creating the world; stopping the server and inserting your datapack into the worlds `datapack` folder; starting the server back up again.

Datapacks are a pretty common method of configuration for mods now. They are flexible, easy to use, allow for more complete customisability than standard config files and don't have to be used on the client, making them ideal for servers.

Hope that helps,
Thanks.

**Comment by Mossza324** [comment]
The guide linked seems to be missing, where'd it go?

**Comment by CleverNucleus** [comment]
@Mossza324 I actually don't remember, sorry. It was essentially [this](https://github.com/CleverNucleus/RelicEx/issues/27#issuecomment-1356240706) I think.
