### ISSUE TITLE
Suggestion: Add the ability to set attribute probabilities for specific slots

### ISSUE THREAD

**Issue by ghost** [CleverNucleus/RelicEx#22]
It would be nice to be able to set different attribute chances for different pieces of gear, for example making it so rings don't roll armour but chest pieces and helmets always roll armour.

**Comment by CleverNucleus** [comment]
Hi there,
I quite like this idea. My mod group and I would probably never use this, as our preferences tend to be the default that is shipped with the mod, but I do think this would be cool to have as a datapack config option.
Thank you for the suggestion, I'll look to implement it within a few releases.

**Comment by CleverNucleus** [comment]
Alternative solution: Relics can now be affixed to armour pieces with the latest release, making it so that you can always wear your favourite armour set and benefit from Relics.
