### ISSUE TITLE
Suggestion: Add the ability to add certain modifiers at the end based on the items rarity

### ISSUE THREAD

**Issue by ghost** [CleverNucleus/RelicEx#23]
By this I mean for example not rolling armour and toughness normally. Instead waiting for the other modifiers to roll, then calculating the rarity then rolling a based on that rarity.

Specifically what I'm trying to achieve would be a way to make it so all `rare` items have similar armour and toughness to iron armour for example.

Obviously this could be extended to other stats as well, but I think the biggest use case is armour and toughness.

**Comment by CleverNucleus** [comment]
Hi again,
If I understand correctly, you essentially want rarity to be calculated as normal, but armour and armour toughness would be exempt from this calculation and their values would be static for each of the seven tiers of relic?

I appreciate the suggestion but I am going to have to give this one a miss.
Thanks.

**Comment by ghost** [comment]
I guess not really static exactly. This was sort of me trying to solve an issue with the current system on harder difficulties. 

Specifically not having armour on say a chest piece can be really really rough at harder difficulties. 

So what I was imagining was more along the lines of making it so certain relics (helmets and chest-pieces) were guaranteed to roll at least enough armour and toughness to keep up with their none relic competitors. 

Like a rare chest-piece always rolls at least as much armour as an iron chest piece, but can still potentially roll more.

Obviously something like this will be achievable once you implement #22 but that doesn't allow me the granular control I'm looking for. Like if I get a legendary item I want to be able to use it, but currently quite often I can't afford to give up the armour to slot it in. So if instead I could, for example, guarantee all rares are at least as good as leather, and all mythical are at least as good as diamond, that would allow some more freedom in slot choices.

I guess another way of wording it would be to put a minimum roll for certain attributes based on the rarity of the relic.
