### ISSUE TITLE
Datapack seemingly not affecting values

### ISSUE THREAD

**Issue by ghost** [CleverNucleus/RelicEx#24]
I created this datapack [testing_pack.zip](https://github.com/CleverNucleus/RelicEx/files/9713401/testing_pack.zip) but it doesn't seem to be changing anything. In theory assuming I'm reading the help documentation correctly this should make every relic that drops have 10 armour. However I am noticing no change. I tried this in a fresh install with the bare minimum mods needed (RelicEx and it's dependencies).

**Comment by CleverNucleus** [comment]
Hi there,
It is currently not possible to ensure that every Relic item has Armour or Armour Toughness, or indeed any specific attribute. What you have done is increased the *likelihood* (or weight) that a Relic item will spawn with Armour. 

Think of it this way: if we have five attributes with the rarities (weights) 10, 65, 50, 80 and 100, the attribute with 100 is most likely to be attached to a given Relic item, followed by 80, 65 etc., but it is not *guaranteed*. It is not a fractional system where you have everything adding up to 100% - rather, these values are relative to each other; in other words, comparative rarity.

I hope that helps,
Thanks.
