### ISSUE TITLE
Chestplates and Helmets Don't work in Extra Slots

### ISSUE THREAD

**Issue by Astraios117** [CleverNucleus/RelicEx#26]
It seems these relics must replace armor and they don't work in any additional slots. Most relics don't provide armor and the ones that do don't provide that much, making them nonviable very early on. It would be awesome if there was an additional helmet and chestplate slot so relics could stack with armor, making them viable to use, or if they worked with the additional slots from other trinket mods like artifacts

**Comment by CleverNucleus** [comment]
Hi there,
Helmet and Chestplate relics can only fit into the regular Helmet and Chestplate armor slots. You can affix Helmet and Chestplate relics to Helmet and Chestplate armor, allowing you to wear regular vanilla/modded armor whilst continuing to benefit from the relic's attribute bonus.

Ensure that you have a Helmet armor piece equipped, then hold a Helmet relic with your main hand and _sneak-rightclick_. This will merge the relic with the armor piece.

Hope that helps,
Thanks.

**Comment by Astraios117** [comment]
Ah I see, I'm dumb I didn't read through the github description just the curseforge one. I don't see a way to un affix them though, is affixing them permanent?

**Comment by CleverNucleus** [comment]
The affixing is permanent.
