### ISSUE TITLE
[Suggestion] Alternate Way to attach relics to Armour

### ISSUE THREAD

**Issue by Tr33stan** [CleverNucleus/RelicEx#29]
Currently running a pretty extensive modlist as part of a largescale fabric modpack that I have created and use for a server, and have noticed that many client-tweak mods intrinsically add shift+right click as an armour hotswap bind that I for the life of me cannot disable, and this makes binding relics to armour impossible.

I am not aware of the way in which you get the items to merge internally, but perhaps either the option to change the keybind for binding, or providing an additional method (Smithing Table perhaps?) would be beneficial to avoid possible keybind conflicts like this.

On that note, this is just a suggestion, hope you haven't been too swamped with requests or having to fix bugs over this recent christmas/new years and managed to get some rest :)

**Comment by CleverNucleus** [comment]
Hi there,
This is completely valid and I was thinking along those lines too. I plan to switch to using the Smithing Table  for the next release.

We can leave this issue open so I don't forget. I'll close it when I output the release.
Hope that helps,
Thanks.

**Comment by CleverNucleus** [comment]
As of releases 3.1.6 and 3.2.7 for Minecraft 1.18.2 and 1.19.2, respectively, Relics can be affixed to armour using a Smithing Table instead of the old *sneak+right-click* behaviour.

**Comment by Tr33stan** [comment]
Thank you for the quick response!
