### ISSUE TITLE
All health gained from stats/relics is lost upon taking any damage

### ISSUE THREAD

**Issue by Tabbyfip** [CleverNucleus/RelicEx#3]
Minecraft 1,17,1
Fabric: 0.11.7
Mods: PlayerEx(3.0.6), RelicEx(3.0.1), and their requirements. Trinkets Fabric(3.0.4), Data Attributes(1.0.6)

Bug: -All- extra hearts earned through constitution/relics are lost upon a single hit when a Relic with +Health is equipped. Taing any amount of damage for instance will hit you for all of your non-default health while wearing a relic with +health/+con on it. 

How to Reproduce: Give yourself about 10-20 levels, put enough points into constitution for a few extra hearts to see the difference, I'd say around 10 extra hearts. Equip -one- relic that has +health or +con on it, you will immediately take damage for all extra health gained from relics and stats combined. Heal up to full health, have 20 or so hearts combined with Relics & Stats, then take any damage.

PS: Another note entirely would be health not working well with other mods that also add health, but in this example, I only used the requirements for PlayerEx and RelicEx

**Comment by Tabbyfip** [comment]
I updated to the newest version of fabric as well this time. (Fabric 0.12.3) While the problem isn't -as- bad it seems there are a few items that will still break health damage. For instance, this first relic (an amulet) doesn't break the damage to health calculation. 

![doesntbreakhealth](https://user-images.githubusercontent.com/93576341/140474788-f917b0e3-cd03-4cad-9c05-345fb80a79a3.png)

Whereas this helmet most certainly will.
![Doesbreakhealth](https://user-images.githubusercontent.com/93576341/140474898-403121ec-867a-4743-8641-a3faa20f44c8.png)

Both have +health on them but varying amounts, but the +%con items seem to be having the same bug as well! It's just more rare to find these items that break the health bar in the newer fabric I feel but it still persists.

**Comment by CleverNucleus** [comment]
Hi there,
Thanks for the detailed report. I'll look into it and get back to you.

**Comment by CleverNucleus** [comment]
Hi again,
I've spent some time testing, and I've verified the issue.

The bug is only present with armour type relics (i.e. not trinkets). I've taken an extra couple of days to come up with a solution before replying, but no dice I'm afraid.

I have _some_ idea about what's causing the bug, but I think it's an underlying issue with Data Attributes, which makes it hard to solve.

I'll probably not manage to come up with a solution before 1.18 drops, at which point I'm aiming to rework everything after receiving some design considerations from other developers.

Thank you for taking the time out to bring this to my attention, sorry I couldn't be of more help.

**Comment by Lorelando** [comment]
A temporary fix might be to prevent all attributes that modify health on body armor and helmets.

**Comment by Tabbyfip** [comment]
Ah, that's true! Might be a good solution for now until there's another update to work with. Honestly, in my case, I just tell my server not to use Armor Relics with +HP/CON on them for now which is fine if people are aware of it. Though I think your best bet would be to hotfix just in case just removing HP/CON from the armor tables until more time and incentive is added by a new update or features.

It's honestly up to you and the time required! Removing the HP/CON would prevent further reports or bugs involving this minor'ish issue while leaving it in with a simple disclaimer would be easier until you get to sit down and work with a new update.

This definitely isn't game-breaking, just requires a workaround or awareness of it!

**Comment by CleverNucleus** [comment]
Yeah @Lorelando I think that's a good idea; I will try and release a hotfix before the end of this week.

**Comment by CleverNucleus** [comment]
Fixed.
