### ISSUE TITLE
Possible Incompat with TieredZ - Can't use smithing table to apply Relic to tiered modded item

### ISSUE THREAD

**Issue by jmadarg** [CleverNucleus/RelicEx#32]
***MC version:*** 1.19.2 Fabric
***Modpack:*** Medieval MC [FABRIC] - MMC1
***Problem:*** When trying to ass a Relic to a modded item that has a tier (TieredZ mod adds tiers to the items like armor/tools/weapons) , the Relic does not add any property. It works fine if the item is vanilla and has a tier, or if the item doesn't have a tier (modded or vanilla). Not always happens, I'm still not able to pinpoint exactly what triggers the problem.

Modded item without any tier:
![image](https://user-images.githubusercontent.com/62086445/213693420-245883a8-2152-414e-a6e9-e892aaae91e5.png)

Modded item with a tier but not working properly:
![image](https://user-images.githubusercontent.com/62086445/213693451-7c494dbb-cda9-4fdf-bff7-19882b5e4c83.png)

Modded item with a tier but working properly (was a different set of properties on the tier and a different Relic):
![image](https://user-images.githubusercontent.com/62086445/213696561-84af45a1-4e65-4e84-be42-b15911cf47e8.png)

I opened an issue on the TieredZ github too https://github.com/Globox1997/tiered/issues/43

**Comment by Yasamashi** [comment]
I also wanted to add that you can't join a vanilla armor already found enchanted (e.g.: found in a dungeon chest and the likes) and a relic in the same way: the vanilla armor doesn't get the stats even if the action is possible. Screenshots attached.

![2023-01-20_15 30 28](https://user-images.githubusercontent.com/56409190/213728726-a2df8d7e-a25e-443d-84ec-0b6ce33f87e3.png)
![2023-01-20_15 30 32](https://user-images.githubusercontent.com/56409190/213728775-43a05bd2-58ef-421e-89a3-e63a7fac562a.png)
![2023-01-20_15 30 37](https://user-images.githubusercontent.com/56409190/213728867-fa655258-c3dd-4c42-acb3-097638661fb9.png)
![2023-01-20_15 34 09](https://user-images.githubusercontent.com/56409190/213728892-0abb454a-7bbd-4859-93ef-60ba31df0b67.png)
![2023-01-20_15 34 19](https://user-images.githubusercontent.com/56409190/213728942-e18d3c56-2e47-4777-a0b5-a4d710acce8b.png)
![2023-01-20_15 34 16](https://user-images.githubusercontent.com/56409190/213728991-a7aa1b66-1591-4628-94a2-3dc239839698.png)

**Comment by Totitodios** [comment]
[Same[](url)]([url](![2023-01-21_03 34 27](https://user-images.githubusercontent.com/123230330/213847271-f7b2b7e8-b440-428e-b3a7-277c119cba9a.png)))

**Comment by CleverNucleus** [comment]
Hi there @jmadarg @Yasamashi @Totitodios 
I appreciate the detailed report; I'll look into it.
Thanks.

**Comment by ghost** [comment]
Hello, I’d just like to add some clarity here, as I believe there are two separate issues:

@jmadarg ’s example is likely only visual - equipping the item will still apply the relic’s stats to the player even if they aren’t visible. This is likely an issue with tieredZ or a limit with item descriptions as this interaction happens with many other mods. I also feel it’s a fairly minor issue.

However, the examples from @Totitodios and @Yasamashi are different - the items with relics being applied are likely being affected by Dungeon Difficulty, which applies bonuses to looted items, as these screenshots seem to be from Medieval MC Fabric after that mod was added to the pack, and they specify that these items are from a chest (while the Heavy armor from jmadarg’s example was crafting-only at the time)

When a Dungeon Difficulty enhanced item has a relic affixed, it not only does not show its bonuses, but does not apply to the player, as @Yasamashi shows. 

I haven’t yet checked if the NBT from the relic still applies to the new item in the case of the Dungeon Difficulty issue.

**Comment by ghost** [comment]
Just double checked - in the case of Dungeon Difficulty, the NBT does apply, but the bonuses do not, when equipped. 

Here's the item I checked -

![Screen Shot 2023-03-04 at 3 55 23 PM](https://user-images.githubusercontent.com/122633855/222930535-1f5e0bb3-1cf9-4e1b-b97d-2dc5251bf152.png)

The TieredZ stats don't apply either, but that's also present only with Dungeon Difficulty bonuses. I don't know the first thing about these implementations, but it appears Dungeon DIfficulty's AttributeModifiers is interfering with both of these mods. 

If this isn't something that can be resolved, I might suggest making the relic smithing table recipe incompatible with anything with the AttributeModifiers nbt.

**Comment by CleverNucleus** [comment]
Hi @muon-r,
I appreciate your insights. I very recently released an [update](https://github.com/CleverNucleus/RelicEx/releases/tag/v3.0.0-1.19.2) to RelicEx which fixes a [bug](https://github.com/CleverNucleus/RelicEx/issues/37) with how attributes are combined. What version of RelicEx did you use? If not the aforementioned, then bug behaviour may have changed.
Thanks.

**Comment by ghost** [comment]
I’m using the latest update from yesterday, unfortunately this appears unrelated to that fix. It happens both before and after this version

**Comment by CleverNucleus** [comment]
Just to provide update on this: I have identified **exactly** what is happening, and have a couple of routes towards a fix. Hopefully will include this in next release - no exact timeframe as of yet.

**Comment by CleverNucleus** [comment]
Latest release `3.3.1-1.18.2` and `3.3.1-1.19.2` fixes this issue and is available now on Modrinth, pending approval on Curseforge.

**Comment by Globox1997** [comment]
@CleverNucleus how did you resolve this incompatibility with dungeons difficulty?

**Comment by CleverNucleus** [comment]
>how did you resolve this incompatibility with dungeons difficulty?

@Globox1997, it is not yet resolved for Dungeon Difficulty, only TieredZ. There is a separate issue for this [here](https://github.com/CleverNucleus/RelicEx/issues/41).

**Comment by Globox1997** [comment]
k thanks for the info.
