### ISSUE TITLE
New Relic suggestion

### ISSUE THREAD

**Issue by shafschwd** [CleverNucleus/RelicEx#33]
Orb Of Redemption:
`this relic resets all the skill point from a single attribute`

And can you add relic for leg and feet slot the set doesn't feel complete without them.

**Comment by CleverNucleus** [comment]
Hi there,
I appreciate the suggestion. However, this would be surprisingly difficult to implement. I would also argue that this is somewhat redundant with the Orbs of Greater and Lesser Regret. Therefore, I will not be implementing an Orb of Redemption at this time.
Thanks.
