### ISSUE TITLE
Breaking speed not working as intended (?)

### ISSUE THREAD

**Issue by nixord** [CleverNucleus/RelicEx#38]
Hi again! Ive been trying out the breaking speed relics but it seems none of them affect the breaking speed of blocks at all. Ive tried with my modifiers as possible but I cant see any difference in the speed whatsoever. Is the difference supposed to be tiny or is the mod slightly bugged?

**Comment by CleverNucleus** [comment]
Hi there,
The difference should be small, but I think the average value would be noticeable. I will add this to the list of things to take a look at. For now, I would advise trying it with just RelicEx and its dependencies installed to rule out unwanted mod interactions. Additionally, perhaps take a look to see if you notice a difference in block breaking speed if you increase the attribute value using the vanilla command or by a Data Attributes data pack and skilling it with PlayerEx.
Thanks.

**Comment by nixord** [comment]
Ok! Thank you so much! I'd rather use Datapack but I STILL dont know how to
use them. Are they easy to setup?

**Comment by nixord** [comment]
Also I tried using a datapack to change crit behaviour to vanilla but its
throwing me this exception:

java.util.concurrent.CompletionException:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException:
Expected BEGIN_OBJECT but was NUMBER at line 4 column 45 path $.values..

at
java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
~[?:?]

at
java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
~[?:?]

at
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
~[?:?]

at
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
~[?:?]

at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]

at
java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
~[?:?]

at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]

at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
~[?:?]

at
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
~[?:?]

**Comment by CleverNucleus** [comment]
It looks like you've got a syntax issue with your JSON - would you send over your datapack/json file(s) and I can take a look at them? 
Thanks.

**Comment by nixord** [comment]
Sure! Here it is!

**Comment by CleverNucleus** [comment]
Hi, I think that you have not attached anything to your message.

**Comment by nixord** [comment]
Oh whoops, youre right. Well tbh I deleted the whole thing cause it wasnt working at all and got frustrated but ummm... Once I get another datapack going and I get the same error Ill tell you! Also sorry for taking so long to comment on it.

**Comment by CleverNucleus** [comment]
No worries; I'll close this issue for now then, but if the problem reoccurs feel free to reopen it.
