### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by LiviiYS** [CleverNucleus/RelicEx#4]
Whenever I equip any of the trinkets on my server my game crashes

One of my players logs

https://pastebin.com/rYs43kGb

https://pastebin.com/RYpZYw3L

**Comment by CleverNucleus** [comment]
Hi there,
Thanks for reporting this. The error is relatively straightforward to diagnose (thanks for the logs), so I have a good idea of what's going wrong.

Can I ask, when you equip a trinket, does _just_ your client crash (i.e. the server remains running)? Or does the server crash and disconnect your client? Or do both the server and your client crash?

Thanks.

**Comment by LiviiYS** [comment]
> Hi there,
> Thanks for reporting this. The error is relatively straightforward to diagnose (thanks for the logs), so I have a good idea of what's going wrong.
> 
> Can I ask, when you equip a trinket, does _just_ your client crash (i.e. the server remains running)? Or does the server crash and disconnect your client? Or do both the server and your client crash?
> 
> Thanks.



It is the client that crashes

**Comment by CleverNucleus** [comment]
Fixed with latest release.
