### ISSUE TITLE
[Help] Potion Drop Chance

### ISSUE THREAD

**Issue by Ricenami** [CleverNucleus/RelicEx#45]
Hi, love your mod, 

I wanted to know how I could increase the potion drop chance? I'm aware there's a config for the potion drop chance, but it doesn't seem to increase the chances. Is there any way I could make it through a datapack that the potions are dropped from all hostile mobs? And is it possible to make it so I can choose which type of potion (small, medium, large) is dropped depending on what dimension you are in (overworld = small, nether = medium, and end = large)?

Sincerely,

rice

**Comment by CleverNucleus** [comment]
Hi there,

> I wanted to know how I could increase the potion drop chance

Potion drops have an element of complexity to the configuration; to set it such that potions _always_ drop from mobs, the following configuration must be present:

| Option | Value | Description |
| ------- | ------- | ------------ |
| `mobDropBlacklist` | should have no entries | |
| `mobsDropLootChance` | `100` | Guarantees that the mob will drop _something_ |
| `mobDropIsRelic` | `0` | Sets the __*drop weight__ for relics to 0 |
| `mobDropIsLesserOrbChance` | `0` | Sets the __*drop weight__ for lesser orbs to be 0% |
| `mobDropIsGreaterOrbChance` | `0` | Sets the __*drop weight__ for greater orbs to be 0% |
| `mobDropIsTomeChance` | `0` | Sets the __*drop weight__ for tomes to be 0% |
| `mobDropIsPotionChance` | `100` | Sets the __*drop weight__ for potions to be 100% |

__*drop weight__ is the _chance of the drop being a given item_: as long as there are at least two non-zero weights, then even if one has 100% value the other may still drop. Note that it is still fine to set all these values to like 5% or something, if the weight for potions is 100% they will still drop most of the time.

Additionally, if the player (or entity) that kills the mob has a negative luck attribute value (vanilla luck), then it is impossible for an item to drop.

> potions are dropped from all hostile mobs?

Potions/Items will only drop from entities that are of the `Monster` type i.e., only hostile mobs that inherit this class can drop potions (all vanilla hostile mobs, you can maybe check github repos for modded mobs).

> is it possible to make it so I can choose which type of potion

There is no way to set which size of potion will drop.

Admittedly kind of a backwards configuration system, for now that's all there is - hope that helps.

**Comment by Ricenami** [comment]
Hi, sorry to open this thread again, but Is there a mob drop potion blacklist?

**Comment by CleverNucleus** [comment]
> Is there a mob drop potion blacklist?

There is a `mobDropBlacklist` - you can supply a list of mobs and relics, tomes, potions etc. will not drop from them. There is no option to prevent _only_ potions from dropping from certain mobs.

**Comment by Ricenami** [comment]
Thank you for the clarification, blacklisting some mobs does not prevent potions from dropping, I verified the mob id as well.
