### ISSUE TITLE
Please add the modloader tag "forge" for old (forge compatible) versions on curseforge.com

### ISSUE THREAD

**Issue by pavog** [CleverNucleus/RelicEx#5]
RelicEx supports Forge in relicex-1.0.0-1.16.4.jar, right?
Could you please add the modloader tag "forge" for the old versions that are for forge?

**Comment by CleverNucleus** [comment]
Hi again,
I have now added the forge modloader tag to all files that had it missing, across all my mods.
Thanks.

**Comment by pavog** [comment]
Great, thank you! :-)
