### ISSUE TITLE
1.18.2 server crashing on startup

### ISSUE THREAD

**Issue by DadoIrie** [CleverNucleus/RelicEx#7]
No idea whats the issue here ... at first glance because the first line of the error (line 920) `Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode` thought it is one of my datapacks which 've done something wrong so I disabled them in order to check if I'm right ... nope
upon further reading can spot relicex being called out a few times ... hope the log tells what the issue here is (as I have got no idea)

https://mclo.gs/R6lxMZL

**Comment by CleverNucleus** [comment]
Hi there,
Should be fixed now with the latest release.
Thanks.
