### ISSUE TITLE
1.18.2 server crashes when disconnecting client

### ISSUE THREAD

**Issue by DadoIrie** [CleverNucleus/RelicEx#8]
as the title says 
relicex might cause conflicts with village guard as when I'm disconnecting from the server the server crashes

https://mclo.gs/orsRYKy

**Comment by DadoIrie** [comment]
Tested it 2 times with relicex and 2 times without just to be sure

**Comment by CleverNucleus** [comment]
Yeah this is due to RelicEx, I'll output a fix soon.

**Comment by CleverNucleus** [comment]
Releases on curseforge and modrinth pending.
